#!/usr/bin/env bash
STATUS=$(nmcli | grep  $(nmcli device show | head -n1 | cut -d$' ' -f26) | awk 'FNR == 1 {print $2}')
SSID=$(iwgetid | awk -F '"' '{ print $2 }')
STRENGTH=$(awk 'NR==3 {printf("%.0f",$3*10/7)}' /proc/net/wireless)
DEFAULT_NETWORK_INTERFACE=$(nmcli device show | head -n1 | cut -d$' ' -f26)

if ls /sys/class/net/$DEFAULT_NETWORK_INTERFACE/wireless
then
export DEFAULT_NETWORK_TYPE=wireless
else
export DEFAULT_NETWORK_TYPE=wired
fi

if [[ -z $SSID ]]
then
	export SSID=$DEFAULT_NETWORK_INTERFACE
fi

toggle() {
    if [[ "$DEFAULT_NETWORK_TYPE" == wireless ]]
    then
	    if [[ $STATUS == "connected" ]]; then
	        nmcli d disconnect $DEFAULT_NETWORK_INTERFACE
	        notify-send --icon=window-close --urgency=normal "Wi-Fi" "Wi-Fi has been turned off!"
	    else
	        nmcli d connect $DEFAULT_NETWORK_INTERFACE
	        notify-send --icon=checkmark --urgency=normal "Wi-Fi" "Wi-Fi has been turned on, you are back online!"
	    fi
    else
	    if [[ $STATUS == "connected" ]]; then
	        nmcli d disconnect $DEFAULT_NETWORK_INTERFACE
	        notify-send --icon=window-close --urgency=normal "Ethernet" "Ethernet has been turned off!"
	    else
	        nmcli d connect $DEFAULT_NETWORK_INTERFACE
	        notify-send --icon=checkmark --urgency=normal "Ethernet" "Ethernet has been turned on, you are back online!"
	    fi
    fi
}

icon() {
    if [[ "$DEFAULT_NETWORK_TYPE" == wireless ]]
    then
	    if [[ "$STRENGTH" -ge "80" ]]; then
	        echo "󰤨"
	    elif [[ "$STRENGTH" -ge "60" ]]; then
	        echo "󰤥"
	    elif [[ "$STRENGTH" -ge "40" ]]; then
	        echo "󰤢"
	    elif [[ "$STRENGTH" -ge "20" ]]; then
	        echo "󰤟"
	    elif [[ "$STRENGTH" -ge "0" ]]; then
	        echo "󰤯"
	    else
	        echo "󰤭"
	    fi
    else
    	echo "🖧"
    fi
}

status() {
    if [[ "$DEFAULT_NETWORK_TYPE" == wireless ]]
    then
	    if [[ $STATUS == "connected" ]]; then
	        echo $SSID
	    else
	        echo Disconnected
	    fi
    else
	    if [[ $STATUS == "connected" ]]; then
	        echo $SSID
	    else
	        echo Disconnected
	    fi
    fi
}

class() {
    if [[ $STATUS == "connected" ]]; then
    	echo "󰤨"
    else
    	echo "󰤭"
    fi
}

if [[ $1 == "--toggle" ]]; then
    toggle
elif [[ $1 == "--icon" ]]; then
    icon
elif [[ $1 == "--status" ]]; then
    status
elif [[ $1 == "--class" ]]; then
    class
fi
